# -*- coding: utf-8 -*-
"""Workshop-day-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aa9O7C76P6kC6ZzCPkF5YMTH81EHDM06

# Python Workshop for Physics Students by SPS!

## Today is:

## Schedule:

- Every friday from 1:30 P.M. to 3:30 P.M.


## Instructors:
- Aldo
- Tadeo
- Byron J. Encinas Velázquez

## What we'll learn today

- [ ] Discussing the Standard Library
  - OS and SYS library
- [ ] Creating Libraries
- [ ] Classes
- [ ] Erros Typing and Catching
- [ ] Context Managers
- [ ] Collections (new data types)
- [ ] Functools (new data types)
- [ ] Wrappers

# [OS and SYS Libraries ](https://docs.python.org/3/library/index.html)

Maybe one of the most important libraries to communicate back and forth between your machine and your program.

# Custom Datatypes

We know Lists, Tuples, Integers, Float, Boolean, etc.

What if we want a new datatype to help us solve one specific problem?

"""

# This is Joe Harris, let's make him as an object

class Human:
  def __init__(self, name: str):
    self.name = name

''' Wait! Joe is more than just a name! '''

class Human:
  def __init__(self, name: str, mother=None, father=None):
    self.name = name
    self.parents={"Mother": mother, "Father": father}

# Now he has parents, but in case we don't say their names, it'll be None as default

# Maybe he has sibilings

class Human:
  def __init__(self, name: str, mother=None, father=None):
    self.name = name
    self.parents={"Mother": mother, "Father": father}
    self.sibiling = dict()

"""# Creating Custom Libraries

We'll work this part doing our own minimalistic library

Our idea is to make a library that makes complex number operations

## <font color='white'>We highly encourage you to try some of this concepts in your machine while we are discussing and explaining them</font>
"""

import CustomLibrary




"""# Extra Resources

- [Essentials of the Python Standard Library with examples](https://docs.python.org/3/tutorial/stdlib.html)
- []()
- []()
- []()
"""